program MTTools;

uses
  Vcl.Forms,
  DBConfigDTO in 'src\DTO\DBConfigDTO.pas',
  ConfigController in 'src\controller\ConfigController.pas',
  Bcrypt in 'lib\Bcrypt.pas',
  DBHelper in 'src\util\DBHelper.pas',
  RepositoryBase in 'src\util\RepositoryBase.pas',
  UserDTO in 'src\DTO\UserDTO.pas',
  UserController in 'src\controller\UserController.pas',
  Session in 'src\infra\Session.pas',
  MessageHelper in 'src\util\MessageHelper.pas',
  Logging in 'src\infra\Logging.pas',
  PermissionsController in 'src\controller\PermissionsController.pas',
  DBConfigModel in 'src\model\DBConfigModel.pas',
  PermissionGroupModel in 'src\model\PermissionGroupModel.pas',
  Permissions in 'src\model\Permissions.pas',
  UserModel in 'src\model\UserModel.pas',
  DBConfigRepositoryJSON in 'src\repository\implementation\DBConfigRepositoryJSON.pas',
  UserRepository in 'src\repository\implementation\UserRepository.pas',
  CRUDRepositoryInterface in 'src\repository\interface\CRUDRepositoryInterface.pas',
  PermissionGroupDTO in 'src\DTO\PermissionGroupDTO.pas',
  DBConfigRepositoryInterface in 'src\repository\interface\DBConfigRepositoryInterface.pas',
  PermissionGroupRepository in 'src\repository\implementation\PermissionGroupRepository.pas',
  Dependencies in 'src\infra\Dependencies.pas',
  StorageModel in 'src\model\StorageModel.pas',
  StorageRepository in 'src\repository\implementation\StorageRepository.pas',
  StorageController in 'src\controller\StorageController.pas',
  StorageDTO in 'src\DTO\StorageDTO.pas',
  SupplierModel in 'src\model\SupplierModel.pas',
  CNPJ in 'src\model\CNPJ.pas',
  SupplierRepository in 'src\repository\implementation\SupplierRepository.pas',
  SupplierController in 'src\controller\SupplierController.pas',
  SupplierDTO in 'src\DTO\SupplierDTO.pas',
  ToolTypeModel in 'src\model\ToolTypeModel.pas',
  ToolTypeRepository in 'src\repository\implementation\ToolTypeRepository.pas',
  ToolTypeController in 'src\controller\ToolTypeController.pas',
  ToolTypeDTO in 'src\DTO\ToolTypeDTO.pas',
  ToolModel in 'src\model\ToolModel.pas',
  ToolRepository in 'src\repository\implementation\ToolRepository.pas',
  PurchaseOrderModel in 'src\model\PurchaseOrderModel.pas',
  UserRepositoryInterface in 'src\repository\interface\UserRepositoryInterface.pas',
  PermissionGroupRepositoryInterface in 'src\repository\interface\PermissionGroupRepositoryInterface.pas',
  SupplierRepositoryInterface in 'src\repository\interface\SupplierRepositoryInterface.pas',
  ToolTypeRepositoryInterface in 'src\repository\interface\ToolTypeRepositoryInterface.pas',
  StorageRepositoryInterface in 'src\repository\interface\StorageRepositoryInterface.pas',
  ToolRepositoryInterface in 'src\repository\interface\ToolRepositoryInterface.pas',
  CNPJApiInterface in 'src\repository\interface\CNPJApiInterface.pas',
  ImplCnpja in 'src\repository\implementation\ImplCnpja.pas',
  LoginView in 'src\view\LoginView.pas' {formLogin},
  DBConnection in 'src\infra\DBConnection.pas' {Connection: TDataModule},
  MainView in 'src\view\MainView.pas' {formMain},
  DBConfigView in 'src\view\DBConfigView.pas' {formDBConfig},
  UserView in 'src\view\UserView.pas' {formUser},
  MenuView in 'src\view\MenuView.pas' {formMenu},
  PermissionsView in 'src\view\PermissionsView.pas' {formPermissions},
  SupplierView in 'src\view\SupplierView.pas' {formSupplier},
  ToolTypeView in 'src\view\ToolTypeView.pas' {formToolType},
  StorageView in 'src\view\StorageView.pas' {formStorage},
  PurchaseOrderRepositoryInterface in 'src\repository\interface\PurchaseOrderRepositoryInterface.pas',
  PurchaseOrderRepository in 'src\repository\implementation\PurchaseOrderRepository.pas',
  PurchaseOrderController in 'src\controller\PurchaseOrderController.pas',
  PurchaseOrderDTO in 'src\DTO\PurchaseOrderDTO.pas',
  OrderView in 'src\view\OrderView.pas' {formOrder},
  ReportRepositoryInterface in 'src\repository\interface\ReportRepositoryInterface.pas',
  ReportRepository in 'src\repository\implementation\ReportRepository.pas',
  ReportsView in 'src\view\ReportsView.pas' {formReports},
  ReportController in 'src\controller\ReportController.pas',
  ServiceOrderModel in 'src\model\ServiceOrderModel.pas',
  ServiceOrderDTO in 'src\DTO\ServiceOrderDTO.pas',
  ServiceOrderRepositoryInterface in 'src\repository\interface\ServiceOrderRepositoryInterface.pas',
  ServiceOrderRepository in 'src\repository\implementation\ServiceOrderRepository.pas',
  ServiceOrderController in 'src\controller\ServiceOrderController.pas',
  ToolController in 'src\controller\ToolController.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TConnection, Connection);
  Application.CreateForm(TformMain, formMain);
  Application.Run;
end.
